### PR TITLE
Fix ED25519 client certificate

### LINKED ISSUE #469: Ed25519 keys are not fully supported.
I first noticed this issue trying to self sign a certificate with an Ed25519 key.  Ed25519 keys do not work for self-signing client certificates.

On the client:
```
handshake error: alert: Alert Fatal: BadCertificate
```

On the server:
```
handshake error: dtls fatal: expected and actual key signature do not match
```

But that is just the proximate problem I am having.  Several tests fail if you apply this diff, which switches to ed25519 keys in the `selfsigned` package.

```
diff --git a/pkg/crypto/selfsign/selfsign.go b/pkg/crypto/selfsign/selfsign.go
index 581e0a2..e3b57ac 100644
--- a/pkg/crypto/selfsign/selfsign.go
+++ b/pkg/crypto/selfsign/selfsign.go
@@ -5,7 +5,6 @@ import (
        "crypto"
        "crypto/ecdsa"
        "crypto/ed25519"
-       "crypto/elliptic"
        "crypto/rand"
        "crypto/rsa"
        "crypto/tls"
@@ -20,17 +19,16 @@ var errInvalidPrivateKey = errors.New("selfsign: invalid private key type")

 // GenerateSelfSigned creates a self-signed certificate
 func GenerateSelfSigned() (tls.Certificate, error) {
-       priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
+       _, priv, err := ed25519.GenerateKey(rand.Reader)
        if err != nil {
                return tls.Certificate{}, err
        }
-
        return SelfSign(priv)
 }

 // GenerateSelfSignedWithDNS creates a self-signed certificate
 func GenerateSelfSignedWithDNS(cn string, sans ...string) (tls.Certificate, error) {
-       priv, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
+       _, priv, err := ed25519.GenerateKey(rand.Reader)
        if err != nil {
                return tls.Certificate{}, err
        }
```

Failing tests:
```
--- FAIL: TestHandshakeWithAlert (0.41s)
    --- FAIL: TestHandshakeWithAlert/SignatureSchemesNoIntersection (0.00s)
--- FAIL: TestClientCertificate (0.42s)
    --- FAIL: TestClientCertificate/parallel (0.01s)
        --- FAIL: TestClientCertificate/parallel/NoClientCert_cert (0.00s)
        --- FAIL: TestClientCertificate/parallel/RequireAnyClientCert (0.00s)
        --- FAIL: TestClientCertificate/parallel/VerifyClientCertIfGiven_cert (0.00s)
        --- FAIL: TestClientCertificate/parallel/RequireAndVerifyClientCert (0.00s)
        --- FAIL: TestClientCertificate/parallel/RequestClientCert_cert (0.00s)
--- FAIL: TestServerCertificate (0.43s)
    --- FAIL: TestServerCertificate/parallel (0.02s)
        --- FAIL: TestServerCertificate/parallel/good_ca_skip_verify_custom_verify_peer (0.00s)
        --- FAIL: TestServerCertificate/parallel/good_ca_verify_custom_verify_peer (0.00s)
--- FAIL: TestErrorsTemporary (0.00s)
```

### PR DESCRIPTION
**Pull request by daenney**
#### Description

We were incorrectly hashing the handshakeBodies and passing that into Sign. However, for ed25519 you're not supposed to do that, it's part of the signature scheme (aside from the fact that it also uses SHA-512, not SHA-256).

This should now result in ED25519 client certificates working correctly.

#### Reference issue
Fixes #469

### CODE REVIEW

**Review by Sean-Der — APPROVED** [review]
Bug fix on a Sunday can’t beat that service:)

File: crypto.go [hunk 1]
```diff
@@ -117,7 +117,13 @@ func generateCertificateVerify(handshakeBodies []byte, privateKey crypto.Private
...
 	case ed25519.PrivateKey:
 		// https://crypto.stackexchange.com/a/55483
-		return p.Sign(rand.Reader, hashed, crypto.Hash(0))
+		// [..] You do not have to hash the inputs to Ed25519 because hashing is already
+		// part of Ed25519 itself. If you do hash inputs in advance, you become vulnerable
+		// to collisions in the hash function you use. [..]
+		//
+		// ed25519.PrivateKey.Sign(): signs the given message with priv. Ed25519 performs
+		// two passes over messages to be signed and therefore cannot handle pre-hashed messages.
+		return p.Sign(rand.Reader, handshakeBodies, crypto.Hash(0))
```
Comment (at-wat) [inline crypto.go:126]: It looks better to skip https://github.com/pion/dtls/pull/470/files#diff-69c5c48c1da9bf0e59ac32c7d0c0089fee30329073ffcc86cf7200f224f44ecfR111-R115 which isn't used in this path

File: crypto.go [hunk 2]
```diff
@@ -117,7 +117,13 @@ func generateCertificateVerify(handshakeBodies []byte, privateKey crypto.Private
 	switch p := privateKey.(type) {
 	case ed25519.PrivateKey:
 		// https://crypto.stackexchange.com/a/55483
-		return p.Sign(rand.Reader, hashed, crypto.Hash(0))
+		// [..] You do not have to hash the inputs to Ed25519 because hashing is already
+		// part of Ed25519 itself. If you do hash inputs in advance, you become vulnerable
+		// to collisions in the hash function you use. [..]
+		//
+		// ed25519.PrivateKey.Sign(): signs the given message with priv. Ed25519 performs
+		// two passes over messages to be signed and therefore cannot handle pre-hashed messages.
```
Comment (at-wat) [inline crypto.go:125]: Maybe better to refer https://pkg.go.dev/crypto/ed25519#PrivateKey.Sign
> Sign signs the given message with priv. Ed25519 performs two passes over messages to be signed and therefore **cannot handle pre-hashed messages**.

Comment (daenney) [reply crypto.go:125]: I'm not sure I understand, that's already in the comment? Or do you mean remove the Stackexchange link entirely?

File: crypto.go (hunk 1 above)
Comment (daenney) [reply crypto.go:126]: GitHub is doing something wrong for me I think because that link ends up in the middle of `e2e_test.go` without highlighting anything. What do you want us to skip?

Comment (at-wat) [reply crypto.go:126]: https://github.com/pion/dtls/blob/8f9e598d8c5a129bc234f26abe7fdcf21b884626/crypto.go#L111-L115
`hashed` is not used in this `case`.

File: crypto.go (hunk 2 above)
Comment (at-wat) [reply crypto.go:125]: I think it's better to refer only official API documents and RFCs rather than someone's stackexchange answer. (not very strong opinion)
At least we should add the source of reference of L124-125.

File: crypto.go (hunk 1 above)
Comment (daenney) [reply crypto.go:126]: Ah, right yes. Lets fix that!

**Review by at-wat — APPROVED** [review]
LGTM:+1:
